### ISSUE TITLE
Feat(eos_cli_config_gen): Order config output closer to EOS config order

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#1572]
### Enhancement summary

A number of config is just out of order when generating configuration syntax

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

An example `logging host` should be between `logging console` and `logging format`

### Describe the solution you would like

Reorder config output and correct ! placement.

- [X] DHCP Relay #1576 
- [X] Logging #1577 
- [X] AAA #1578
- [X] Port-Channel interface mlag #1580
- [X] Virtual-router address & address virtual (vlan_interfaces) #1579
- [X] BGP allowas-in & network statements (possibly vlan order) ##1603
- [X] Ethernet interface config order #1599
- [X] DNS/hostname/domain lookup order #1589
- [X] Management Order #1580 
- [X] Community-list Order #1607
- [X] No ip icmp redirect order #1608

### Additional context

No template logic will be changed, just the order of config.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
