### ISSUE TITLE
CI Enhancement Tracking

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#244]
# CI Enhancement Tracking

## Complete eos_cli_config_gen Coverage

- [x] Initial Molecule implementation: PR #188
- [x] Implement molecule scenario for eBGP underlay PR #188
- [x] Implement molecule scenario for eBGP underlay with JSON data PR #188 / Issue #180
- [x] Implement molecule scenario for ISIS underlay  PR #188

## Complete eos_l3ls_evpn Coverage

- [x] Initial Molecule implementation: PR#188

## Repo documentation Coverage

- [x] Detect 404 links PR #242
- [x] Test mkdoc configuration is loadable PR #242
- [x] mkdoc deployment PR #160

## Ansible and code sanity

- [x] Pre Commit hooks validation PR #142 
- [x] Add ansible-test workflow in CI PR #89 
- [ ] Run ansible-test in PR only when a file part of the collection is updated

## CI Documentation Coverage

- [x] Update PR template PR #243
- [ ] Contribution guide updates
- [ ] PR Auto labeler action PR #266

**Comment by titom73** [comment]
Everything is now tracked in a dedicated project
