### ISSUE TITLE
Support IPv6 only underlay and VTEPs

### ISSUE THREAD

**Issue by mloevner** [aristanetworks/ansible-avd#2860]
### Enhancement summary

Need to support IPv6 only underlay and overlay, with numbered /64 addressing between switches. The only IPv4 addresses within this model should be on the management interfaces and the MLAG peer link IPs.
[dIPv6 sample configs.zip](https://github.com/aristanetworks/ansible-avd/files/11507172/dIPv6.sample.configs.zip)

### Which component of AVD is impacted

eos_designs, eos_cli_config_gen

### Use case example

Customer requirement to use IPv6 everywhere as part of US Federal Presidential Mandate

### Describe the solution you would like

Deployment of IPv6 only underlay and IPv6/Ipv4 overlay.

### Describe alternatives you have considered

I've looked at using RFC5549 support but there are a number of differences, like numbered interfaces and IPv6 only VTEPs.

## Task List

- [ ] Remove all underlay IPv4 addresses
- [ ] Remove all IPv4 Loopback addresses (Lo0 and Lo1)
- [ ] Ensure all IPv6 addresses are /64 (there can be no /127 or /128; Except /128 on Loopbacks)
- [ ] Have all underlay eBGP sessions established using IPv6 addresses
- [ ] Have all overlay eBGP EVPN sessions established using Lo0 IPv6 address

**Comment by mloevner** [comment]
Some items that we cant complete with the existing model:

Remove all underlay IPv4 addresses
Remove all IPv4 Loopback addresses (Lo0 and Lo1)
Ensure all IPv6 addresses are /64 (there can be no /127 or /128; Except /128 on Loopbacks)
Have all underlay eBGP sessions established using IPv6 addresses
Have all overlay eBGP EVPN sessions established using Lo0 IPv6 address

**Comment by mc1101** [comment]
Through further discussions with the customer, IPv6 loopback addresses should be /64s as well.

**Comment by mc1101** [comment]
Also need to add IPv6 MLAG peer addresses (added in 4.31.1)
